global using PostApi = OsuDroid.Post.Api2;
global using static System.Console;
global using System;
global using System.Text;
global using System.Linq;
global using System.Collections.Generic;
global using LamLibAllOver;
global using Entities = OsuDroidLib.Database.Entities;
global using DbBuilder = OsuDroidLib.Database.DbBuilder;
global using Setting = OsuDroidLib.Setting;
global using System.Diagnostics.CodeAnalysis;
global using OsuDroidLib;