global using static System.Console;
global using System;
global using System.Text;
global using System.Linq;
global using System.Collections.Generic;
global using System.Linq.Expressions;
global using LamLibAllOver;
global using Logger = LamLibAllOver.Logger;
global using OsuDroid.CMT;
global using SavePoco = LamSavePoco.SavePoco;
global using Entities = OsuDroidLib.Database.Entities;
global using FnEntity = OsuDroid.Database.TableFn;
global using DbBuilder = OsuDroidLib.Database.DbBuilder;
global using Env = OsuDroidLib.Env;